
INSERT INTO paises (numero, nombre, nombreCorto, capital, nacionalidad, idiomas) VALUES
(1,  '🇨🇦 Canadá',                          'CA', 'Ottawa',               'canadiense',         'Inglés, Francés'),
(2,  '🇺🇸 Estados Unidos',                  'US', 'Washington D.C.',      'estadounidense',     'Inglés'),
(3,  '🇲🇽 México',                          'MX', 'Ciudad de México',     'mexicana',           'Español'),
(4,  '🇬🇹 Guatemala',                       'GT', 'Ciudad de Guatemala',  'guatemalteca',       'Español'),
(5,  '🇧🇿 Belice',                          'BZ', 'Belmopán',             'beliceña',           'Inglés, Español'),
(6,  '🇸🇻 El Salvador',                     'SV', 'San Salvador',         'salvadoreña',        'Español'),
(7,  '🇭🇳 Honduras',                        'HN', 'Tegucigalpa',          'hondureña',          'Español'),
(8,  '🇳🇮 Nicaragua',                       'NI', 'Managua',              'nicaragüense',       'Español'),
(9,  '🇨🇷 Costa Rica',                      'CR', 'San José',             'costarricense',      'Español'),
(10, '🇵🇦 Panamá',                          'PA', 'Ciudad de Panamá',     'panameña',           'Español'),
(11, '🇨🇺 Cuba',                            'CU', 'La Habana',            'cubana',             'Español'),
(12, '🇯🇲 Jamaica',                         'JM', 'Kingston',             'jamaicana',          'Inglés'),
(13, '🇭🇹 Haití',                           'HT', 'Puerto Príncipe',      'haitiana',           'Francés, Criollo haitiano'),
(14, '🇩🇴 República Dominicana',            'DO', 'Santo Domingo',        'dominicana',         'Español'),
(15, '🇧🇸 Bahamas',                         'BS', 'Nasáu',                'bahameña',           'Inglés'),
(16, '🇧🇧 Barbados',                        'BB', 'Bridgetown',           'barbadense',         'Inglés'),
(17, '🇹🇹 Trinidad y Tobago',               'TT', 'Puerto España',        'trinitense',         'Inglés'),
(18, '🇦🇬 Antigua y Barbuda',               'AG', 'Saint John',           'antiguana',          'Inglés'),
(19, '🇩🇲 Dominica',                        'DM', 'Roseau',               'dominiquesa',        'Inglés'),
(20, '🇬🇩 Granada',                         'GD', 'Saint George',         'granadina',          'Inglés'),
(21, '🇰🇳 San Cristóbal y Nieves',          'KN', 'Basseterre',           'sancristobaleña',    'Inglés'),
(22, '🇱🇨 Santa Lucía',                     'LC', 'Castries',             'santalucense',       'Inglés'),
(23, '🇻🇨 San Vicente y las Granadinas',    'VC', 'Kingstown',            'sanvicentina',       'Inglés'),
(24, '🇨🇴 Colombia',                        'CO', 'Bogotá',               'colombiana',         'Español'),
(25, '🇻🇪 Venezuela',                       'VE', 'Caracas',              'venezolana',         'Español'),
(26, '🇬🇾 Guyana',                          'GY', 'Georgetown',           'guyanesa',           'Inglés'),
(27, '🇸🇷 Surinam',                         'SR', 'Paramaribo',           'surinamesa',         'Neerlandés'),
(28, '🇪🇨 Ecuador',                         'EC', 'Quito',                'ecuatoriana',        'Español'),
(29, '🇵🇪 Perú',                            'PE', 'Lima',                 'peruana',            'Español, Quechua, Aimara'),
(30, '🇧🇷 Brasil',                          'BR', 'Brasilia',             'brasileña',          'Portugués'),
(31, '🇧🇴 Bolivia',                         'BO', 'Sucre',                'boliviana',          'Español, Quechua, Aimara'),
(32, '🇵🇾 Paraguay',                        'PY', 'Asunción',             'paraguaya',          'Español, Guaraní'),
(33, '🇨🇱 Chile',                           'CL', 'Santiago',             'chilena',            'Español'),
(34, '🇦🇷 Argentina',                       'AR', 'Buenos Aires',         'argentina',          'Español'),
(35, '🇺🇾 Uruguay',                         'UY', 'Montevideo',           'uruguaya',           'Español')
ON CONFLICT (numero) DO UPDATE SET
    nombre       = EXCLUDED.nombre,
    nombreCorto  = EXCLUDED.nombreCorto,
    capital      = EXCLUDED.capital,
    nacionalidad = EXCLUDED.nacionalidad,
    idiomas      = EXCLUDED.idiomas;